### ISSUE TITLE
Pattern Matching issue in reroll_until_rarity.lua

### ISSUE THREAD

**Issue by gpkgpk** [Aussiemon/Darktide-Mods#4]
Pattern Matching issue in safe_find function reroll_until_rarity.lua [https://github.dev/Aussiemon/Darktide-Mods/blob/648060272c624c3891f9571a95721337a8219691/reroll_until_rarity/scripts/mods/reroll_until_rarity/reroll_until_rarity.lua#L22](url)
Partial matching tougness regen with toughness 
E.g. 
![image](https://user-images.githubusercontent.com/4491424/225818151-29dbea81-8eb4-463e-baa2-9676d6dc8849.png)

**Comment by Aussiemon** [comment]
Handled in https://github.com/Aussiemon/Darktide-Mods/commit/b0bc97fdae49d759dbc627d401a09c83eeec7fd0
